----------saipa table---------------
create table saipa(
    id numeric GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50) NOT NULL,
    systems varchar(50) NOT NULL,
    farmon varchar(50) NOT NULL );


insert into saipa(name,systems,farmon) values ('quick','automatic','hidrolic');
commit ;


select * from saipa where id=1;
----------cars table---------------
create table cars(
    id numeric generated by default as identity ,
    company varchar(50),
    color varchar (50)
);

insert into cars(id,company,color) values (1,'BMW','BLACK');
COMMIT;

select * from cars where id=1;
-----------------motors table------------------
create table motors(
    id numeric generated by default as identity ,
company varchar(50),
color varchar(20)
);
insert into motors(id, company, color) values (1,'honda','white');
commit ;


select * from motors where id= 1 ;
--------------condition -----------------------------


SELECT 'name' FROM saipa WHERE id NOT IN (SELECT name FROM saipa WHERE 1=1);
SELECT 'color' FROM cars WHERE id NOT IN (SELECT color FROM cars WHERE 2=2);
SELECT 'company' FROM motors WHERE id NOT IN (SELECT company FROM motors WHERE 3=3);





